# -*- coding: utf-8 -*-
"""SVHN_YOLOV4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r4tfoWkZZJrGEVIUI72L6FJzK7y_m9K2

https://jason-chen-1992.weebly.com/home/-google-colab-yolov41303994

# check GPU information
"""

!/usr/local/cuda/bin/nvcc --version
!nvidia-smi

"""# 測試
測試之前安裝的darknet能不能正常使用
"""

from google.colab import drive
drive.mount('/content/gdrive',force_remount=True)

import os
!ln -s '/content/gdrive/MyDrive/space_Colab' /work1

# Commented out IPython magic to ensure Python compatibility.
# Copy the darknet from Google Drive to Google Colab VM
!cp /work1/space_for_YOLO/darknet.zip /content/darknet.zip
# Unzip the darknet file
!unzip /content/darknet.zip
# go into darknet folder
# %cd darknet

!./darknet detect cfg/yolov4.cfg yolov4.weights data/person.jpg
# show result
import cv2
from google.colab.patches import cv2_imshow
image = cv2.imread('predictions.jpg')
cv2_imshow(image)

"""# 開始訓練"""

try:
  import os
  os.mkdir('/work1/svhn_HW2/weights/')
except FileExistsError:
  print("Direction is exist !!!")

FIRST_TIME = False
if FIRST_TIME:
  !./darknet detector train /work1/svhn_HW2/obj.data /work1/svhn_HW2/yolov4_1124.cfg yolov4.conv.137  -dont_show-map -chart chart.png -dont_show 
else:
  !./darknet detector train /work1/svhn_HW2/obj.data /work1/svhn_HW2/yolov4_1124.cfg /work1/svhn_HW2/weights/yolov4_1124_last.weights -chart chart.png -dont_show





